# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0003_mustbuy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mustbuy',
            table='axf_mustbuy',
        ),
    ]
