# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_foodtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtypes',
            name='typeid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='foodtypes',
            name='typename',
            field=models.CharField(max_length=100),
        ),
    ]
