# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0008_auto_20181102_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtypes',
            name='childtypenames',
            field=models.CharField(max_length=200),
        ),
    ]
